//! Logica di generazione della configurazione

use crate::config::{
    get_basic_opts, get_snippet, get_standard_config_dir, get_user_content, PackageManager,
    PROGRAM_NAME, PROGRAM_VERSION,
};
use crate::types::GenerationResult;
use anyhow::Result;
use chrono::Local;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

// ---------- CREAZIONE SCHELETRO ----------
fn create_skeleton(dest: &Path, pkg: PackageManager, gen_date: &str, no_comments: bool) -> Result<()> {
    fs::create_dir_all(dest)?;

    let init_content = format!(
        r#"print("This configuration was generated by {} on {} with script version {}")

{}

require('user')

{}

-- Put the rest of your configuration here
"#,
        PROGRAM_NAME,
        gen_date,
        PROGRAM_VERSION,
        get_basic_opts(no_comments),
        get_snippet(pkg, no_comments)
    );
    fs::write(dest.join("init.lua"), init_content)?;

    let lua_user_dir = dest.join("lua").join("user");
    fs::create_dir_all(&lua_user_dir)?;
    fs::write(lua_user_dir.join("init.lua"), get_user_content(no_comments))?;

    let readme_content = format!(
        r#"# Neovim Configuration Skeleton

This is a minimal, empty skeleton for Neovim configuration.

## Structure
- `init.lua` - main entry point (includes a commented bootstrap template for {})
- `lua/` - Lua modules
  - `user/` - your custom modules

## Usage
1. Edit `init.lua` to set options and load modules.
2. If you want to use the provided package manager template, uncomment the
   bootstrap block and add your plugins.
3. Place your additional Lua files in `lua/` or its subdirectories.

This skeleton is ready for you to build your own Neovim setup.
"#,
        pkg
    );
    fs::write(dest.join("README.md"), readme_content)?;

    Ok(())
}

// ---------- UTILITY DI FILESYSTEM ----------
fn copy_tree(src: &Path, dst: &Path) -> Result<()> {
    if dst.exists() {
        fs::remove_dir_all(dst)?;
    }
    let mut options = fs_extra::dir::CopyOptions::new();
    options.overwrite = true;
    options.copy_inside = true;
    fs_extra::dir::copy(src, dst, &options)?;
    Ok(())
}

fn remove_tree(path: &Path) -> Result<()> {
    if path.exists() {
        fs::remove_dir_all(path)?;
    }
    Ok(())
}

// ---------- AVVIO NEOVIM ----------
fn run_neovim(config_dir: &Path, quiet: bool) -> Result<()> {
    let nvim_exe = if cfg!(windows) { "nvim.exe" } else { "nvim" };

    #[cfg(windows)]
    {
        let _ = quiet;
        let status = Command::new("cmd")
            .args(&[
                "/C",
                &format!(
                    "set XDG_CONFIG_HOME={} && {}",
                    config_dir.display(),
                    nvim_exe
                ),
            ])
            .status()?;
        if !status.success() {
            anyhow::bail!("Neovim exited with error");
        }
    }

    #[cfg(not(windows))]
    {
        let old_xdg = std::env::var("XDG_CONFIG_HOME").ok();
        std::env::set_var("XDG_CONFIG_HOME", config_dir);
        if !quiet {
            eprintln!("Launching Neovim with XDG_CONFIG_HOME={}", config_dir.display());
        }
        let status = Command::new(nvim_exe).status()?;
        if let Some(old) = old_xdg {
            std::env::set_var("XDG_CONFIG_HOME", old);
        } else {
            std::env::remove_var("XDG_CONFIG_HOME");
        }
        if !status.success() {
            anyhow::bail!("Neovim exited with error");
        }
    }

    Ok(())
}

// ---------- LOGICA PRINCIPALE DI GENERAZIONE ----------
pub fn run_generation(
    pkg: PackageManager,
    deploy: bool,
    run: bool,
    output_dir: Option<&Path>,
    force: bool,
    quiet: bool,
    dry_run: bool,
    no_comments: bool,
    keep: bool,
) -> GenerationResult {
    let mut res = GenerationResult {
        success: false,
        result_path: None,
        error_msg: None,
    };

    let gen_date = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();

    let temp_dir = match tempfile::tempdir() {
        Ok(dir) => dir,
        Err(e) => {
            res.error_msg = Some(format!("Failed to create temp dir: {}", e));
            return res;
        }
    };
    let temp_path = temp_dir.path().to_path_buf();
    let skeleton_path = temp_path.join("nvim");

    if let Err(e) = create_skeleton(&skeleton_path, pkg, &gen_date, no_comments) {
        res.error_msg = Some(format!("Failed to create skeleton: {}", e));
        if !keep {
            let _ = remove_tree(&temp_path);
        } else {
            eprintln!("Temporary directory kept (error): {}", temp_path.display());
        }
        return res;
    }

    if dry_run {
        res.success = true;
        res.result_path = Some(skeleton_path);
        if !keep {
            let _ = remove_tree(&temp_path);
        } else {
            eprintln!("Temporary directory kept (dry-run): {}", temp_path.display());
        }
        return res;
    }

    let final_nvim_dir: PathBuf;
    let parent_for_run: PathBuf;

    if deploy {
        let target = get_standard_config_dir();
        if target.exists() {
            if force {
                let backup = target.with_extension("backup");
                if backup.exists() {
                    let _ = remove_tree(&backup);
                }
                if let Err(e) = fs::rename(&target, &backup) {
                    res.error_msg = Some(format!("Failed to rename existing config: {}", e));
                    if !keep {
                        let _ = remove_tree(&temp_path);
                    } else {
                        eprintln!("Temporary directory kept: {}", temp_path.display());
                    }
                    return res;
                }
                if !quiet {
                    println!("Existing config moved to: {}", backup.display());
                }
            } else {
                if !quiet {
                    println!(
                        "Target directory {} already exists. Use --force to overwrite.",
                        target.display()
                    );
                }
                res.error_msg = Some("Target directory exists and --force not given".to_string());
                if !keep {
                    let _ = remove_tree(&temp_path);
                } else {
                    eprintln!("Temporary directory kept: {}", temp_path.display());
                }
                return res;
            }
        }
        if let Err(e) = copy_tree(&skeleton_path, &target) {
            res.error_msg = Some(format!("Failed to copy skeleton: {}", e));
            if !keep {
                let _ = remove_tree(&temp_path);
            } else {
                eprintln!("Temporary directory kept: {}", temp_path.display());
            }
            return res;
        }
        final_nvim_dir = target.clone();
        parent_for_run = target.parent().unwrap_or(Path::new(".")).to_path_buf();
    } else if let Some(out_dir) = output_dir {
        let dest = out_dir.join("nvim");
        if dest.exists() {
            if force {
                let _ = remove_tree(&dest);
            } else {
                if !quiet {
                    println!(
                        "Output directory {} already exists. Use --force to overwrite.",
                        dest.display()
                    );
                }
                res.error_msg = Some("Output directory exists and --force not given".to_string());
                if !keep {
                    let _ = remove_tree(&temp_path);
                } else {
                    eprintln!("Temporary directory kept: {}", temp_path.display());
                }
                return res;
            }
        }
        if let Err(e) = fs::create_dir_all(out_dir) {
            res.error_msg = Some(format!("Failed to create output dir: {}", e));
            if !keep {
                let _ = remove_tree(&temp_path);
            } else {
                eprintln!("Temporary directory kept: {}", temp_path.display());
            }
            return res;
        }
        if let Err(e) = copy_tree(&skeleton_path, &dest) {
            res.error_msg = Some(format!("Failed to copy skeleton: {}", e));
            if !keep {
                let _ = remove_tree(&temp_path);
            } else {
                eprintln!("Temporary directory kept: {}", temp_path.display());
            }
            return res;
        }
        final_nvim_dir = dest;
        parent_for_run = out_dir.to_path_buf();
    } else {
        final_nvim_dir = skeleton_path.clone();
        parent_for_run = temp_path.clone();
    }

    if run {
        if let Err(e) = run_neovim(&parent_for_run, quiet) {
            res.error_msg = Some(format!("Failed to run Neovim: {}", e));
            if !keep {
                let _ = remove_tree(&temp_path);
            } else {
                eprintln!("Temporary directory kept: {}", temp_path.display());
            }
            return res;
        }
    }

    if run && !deploy && output_dir.is_none() {
        if !keep {
            let _ = remove_tree(&temp_path);
            if !quiet {
                println!("Temporary configuration removed.");
            }
        } else {
            eprintln!("Temporary directory kept (--run): {}", temp_path.display());
        }
    } else {
        if !keep {
            let _ = remove_tree(&temp_path);
        } else {
            eprintln!("Temporary directory kept: {}", temp_path.display());
        }
    }

    res.success = true;
    res.result_path = Some(final_nvim_dir);
    res
}